export const LOCATIONS = [
  { id: "skopje", name: "Скопје", nameEn: "Skopje" },
  { id: "bitola", name: "Битола", nameEn: "Bitola" },
  { id: "kumanovo", name: "Куманово", nameEn: "Kumanovo" },
  { id: "prilep", name: "Прилеп", nameEn: "Prilep" },
  { id: "tetovo", name: "Тетово", nameEn: "Tetovo" },
  { id: "veles", name: "Велес", nameEn: "Veles" },
  { id: "stip", name: "Штип", nameEn: "Štip" },
  { id: "ohrid", name: "Охрид", nameEn: "Ohrid" },
  { id: "gostivar", name: "Гостивар", nameEn: "Gostivar" },
  { id: "kavadarci", name: "Кавадарци", nameEn: "Kavadarci" },
  { id: "strumica", name: "Струмица", nameEn: "Strumica" },
  { id: "kicevo", name: "Кичево", nameEn: "Kičevo" },
  { id: "kocani", name: "Кочани", nameEn: "Kočani" },
  { id: "struga", name: "Струга", nameEn: "Struga" },
  { id: "radovis", name: "Радовиш", nameEn: "Radoviš" },
  { id: "gevgelija", name: "Гевгелија", nameEn: "Gevgelija" },
  { id: "debar", name: "Дебар", nameEn: "Debar" },
  { id: "kriva_palanka", name: "Крива Паланка", nameEn: "Kriva Palanka" },
  { id: "sveti_nikole", name: "Свети Николе", nameEn: "Sveti Nikole" },
  { id: "negotino", name: "Неготино", nameEn: "Negotino" },
  { id: "delcevo", name: "Делчево", nameEn: "Delčevo" },
  { id: "vinica", name: "Виница", nameEn: "Vinica" },
  { id: "resen", name: "Ресен", nameEn: "Resen" },
  { id: "probistip", name: "Пробиштип", nameEn: "Probištip" },
  { id: "berovo", name: "Берово", nameEn: "Berovo" },
  { id: "kratovo", name: "Кратово", nameEn: "Kratovo" },
  { id: "krusevo", name: "Крушево", nameEn: "Kruševo" },
  { id: "makedonski_brod", name: "Македонски Брод", nameEn: "Makedonski Brod" },
  { id: "demir_kapija", name: "Демир Капија", nameEn: "Demir Kapija" },
  { id: "demir_hisar", name: "Демир Хисар", nameEn: "Demir Hisar" },
  { id: "pehcevo", name: "Пехчево", nameEn: "Pehčevo" },
  { id: "valandovo", name: "Валандово", nameEn: "Valandovo" },
  {
    id: "makedonska_kamenica",
    name: "Македонска Каменица",
    nameEn: "Makedonska Kamenica",
  },
];
