import { Listing } from "./types";

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "2019 Toyota Camry - Excellent Condition",
    price: 18500,
    location: "New York",
    category: "Vehicles",
    subcategory: "Cars",
    image: "/placeholder.svg?height=200&width=300&text=Toyota+Camry",
    date: "2 days ago",
    featured: true,
    categoryColor: "text-blue-500",
  },
  {
    id: "2",
    title: "Modern Apartment in Downtown - 2BR",
    price: 450000,
    location: "Los Angeles",
    category: "Real Estate",
    subcategory: "Apartments",
    image: "/placeholder.svg?height=200&width=300&text=Apartment",
    date: "5 hours ago",
    categoryColor: "text-orange-500",
  },
  {
    id: "3",
    title: "iPhone 13 Pro - Like New",
    price: 750,
    location: "Chicago",
    category: "Electronics",
    subcategory: "Phones",
    image: "/placeholder.svg?height=200&width=300&text=iPhone",
    date: "1 day ago",
    categoryColor: "text-purple-500",
  },
  {
    id: "4",
    title: "Vintage Leather Sofa",
    price: 450,
    location: "Houston",
    category: "Home & Garden",
    subcategory: "Furniture",
    image: "/placeholder.svg?height=200&width=300&text=Sofa",
    date: "3 days ago",
    categoryColor: "text-yellow-500",
  },
  {
    id: "5",
    title: "Mountain Bike - Professional",
    price: 1200,
    location: "Phoenix",
    category: "Sports",
    subcategory: "Cycling",
    image: "/placeholder.svg?height=200&width=300&text=Bike",
    date: "12 hours ago",
    categoryColor: "text-red-500",
  },
  {
    id: "6",
    title: "Web Development Services",
    price: null,
    location: "Remote",
    category: "Services",
    subcategory: "Personal",
    image: "/placeholder.svg?height=200&width=300&text=Web+Dev",
    date: "4 days ago",
    categoryColor: "text-indigo-500",
  },
  {
    id: "7",
    title: "Professional DSLR Camera Kit",
    price: 2500,
    location: "Philadelphia",
    category: "Electronics",
    subcategory: "Cameras",
    image: "/placeholder.svg?height=200&width=300&text=Camera",
    date: "1 week ago",
    categoryColor: "text-purple-500",
  },
  {
    id: "8",
    title: "Luxury SUV - 2021 Range Rover",
    price: 85000,
    location: "San Antonio",
    category: "Vehicles",
    subcategory: "Cars",
    image: "/placeholder.svg?height=200&width=300&text=Range+Rover",
    date: "3 days ago",
    categoryColor: "text-blue-500",
  },
  {
    id: "9",
    title: "Gaming PC - High Performance",
    price: 1800,
    location: "San Diego",
    category: "Electronics",
    subcategory: "Laptops",
    image: "/placeholder.svg?height=200&width=300&text=Gaming+PC",
    date: "2 days ago",
    categoryColor: "text-purple-500",
  },
  {
    id: "10",
    title: "Handyman Services - Home Repairs",
    price: null,
    location: "Dallas",
    category: "Services",
    subcategory: "Home Repairs",
    image: "/placeholder.svg?height=200&width=300&text=Handyman",
    date: "6 hours ago",
    categoryColor: "text-indigo-500",
  },
  {
    id: "11",
    title: "Beachfront Property - Investment Opportunity",
    price: 1200000,
    location: "San Jose",
    category: "Real Estate",
    subcategory: "Houses",
    image: "/placeholder.svg?height=200&width=300&text=Beach+House",
    date: "1 month ago",
    featured: true,
    categoryColor: "text-orange-500",
  },
  {
    id: "12",
    title: "Professional Moving Services",
    price: null,
    location: "Chicago",
    category: "Services",
    subcategory: "Moving",
    image: "/placeholder.svg?height=200&width=300&text=Moving",
    date: "5 days ago",
    categoryColor: "text-indigo-500",
  },
  {
    id: "13",
    title: 'MacBook Pro 16" 2021 - M1 Pro',
    price: 1800,
    location: "New York",
    category: "Electronics",
    subcategory: "Laptops",
    image: "/placeholder.svg?height=200&width=300&text=MacBook",
    date: "2 weeks ago",
    categoryColor: "text-purple-500",
  },
  {
    id: "14",
    title: "Commercial Space for Rent",
    price: 3500,
    location: "Los Angeles",
    category: "Real Estate",
    subcategory: "Commercial",
    image: "/placeholder.svg?height=200&width=300&text=Commercial",
    date: "3 weeks ago",
    categoryColor: "text-orange-500",
  },
  {
    id: "15",
    title: "Fitness Training - Personal Coach",
    price: 50,
    location: "Houston",
    category: "Services",
    subcategory: "Personal",
    image: "/placeholder.svg?height=200&width=300&text=Fitness",
    date: "1 day ago",
    categoryColor: "text-indigo-500",
  },
];

// Function to fetch listings with filters
